version: '3.8'
services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    name: pulsar-db
