version: '3.8'

services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    env_file:
      - .env

#  postgres:
#    image: postgres:15
#    container_name: postgres
#    restart: always
#    ports:
#      - '5432:5432'
#    env_file:
#      - .env
#    volumes:
#      - postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql

volumes:
#  postgres:
#    name: pulsar-db
  mysql:
    name: pulsar-db
